### ISSUE TITLE
Date of comments

### ISSUE THREAD

**Issue by srccd** [kopepasah/wp-theme-eighties#33]
The date for comments is not displaying properly. It is showing the post's date instead. Looks like the issue is in **/inc/template-tags.php** within the **eighties_get_time_difference** function. The first couple if/else statements call on _get_the_date_ when they should probably call _$previous_time->format_ instead. Hopefully someone can create a Pull Request with these changes and get it merged. But just wanted to share.

**Comment by kopepasah** [comment]
@srccd this should be fixed in #36
