### ISSUE TITLE
Draft pages and posts visibility issue

### ISSUE THREAD

**Issue by MissFahrenheit** [kopepasah/wp-theme-eighties#34]
Even though draft posts are not included in the post stream of the home page, they are shown in the post navigation (previous/next post), on the bottom part of the post page.

 Also, draft pages are listed in the main navigation.

When clicked, they both redirect to 404 page, correctly.
But shouldn't they be invisible in the first place?
Thanks a lot!

**Comment by kopepasah** [comment]
@MissFahrenheit unfortunately I cannot reproduce this issue. Can you give more details?
